export const USER_ROLES = 1;
export const VENDOR_ROLES = 2;
export const ADMIN_ROLES = 3;


export const DEACTIVATE_STATUS = 0;
export const ACTIVATE_STATUS = 1;

export default {USER_ROLES,VENDOR_ROLES,ADMIN_ROLES,DEACTIVATE_STATUS,ACTIVATE_STATUS}